{{- if .Values.argoServer.cluster }}
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: {{ .Values.gitopsCluster.name }}
  namespace: {{ .Values.gitopsNamespace }}
spec:
  argoServer:
    cluster: {{ .Values.argoServer.cluster | quote }}
    argoNamespace: {{ .Values.gitopsNamespace }}
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: {{ .Values.placement.name }}
    namespace: {{ .Values.gitopsNamespace }}
  gitopsAddon:
    enabled: {{ .Values.gitopsAddon.enabled }}
{{- end }}
