clusterName: ""

namespace: propagation-test

watcher:
  image:
    repository: busybox
    tag: stable
  replicaCount: 1

canary:
  enabled: false
  image:
    repository: hashicorp/http-echo
    tag: latest
  runId: ""
  virtualservice:
    enabled: false
    host: propagation-canary.local
  destinationrule:
    enabled: false

service:
  port: 8080
