apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: {{ .Values.multiclusterHub.resourceName }}
  namespace: {{ .Release.Namespace }}
spec:
{{ toYaml .Values.multiclusterHub.spec | indent 2 }}
