#!/usr/bin/env bash
# Emit an isotope service-graph YAML whose logical clusters match terraform/rosa-hcp cluster_keys
# (same order as terraform output cluster_keys). Graph shape: a chain svc0 -> svc1 -> ... -> svc{N-1}
# across clusters so every ROSA cluster participates.
#
# Usage (repo root):
#   ./isotope-multicluster/001-generate-topology-from-terraform.sh [--terraform-dir DIR] [--namespace NS] \\
#     [-o FILE] [--print-env]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${ROOT}/terraform/rosa-hcp"
NS_DEFAULT="isotope"
OUT=""
PRINT_ENV=0

die() { echo "error: $*" >&2; exit 1; }

usage() {
	cat <<EOF
Usage: $(basename "$0") [options]

  --terraform-dir DIR   Terraform stack with cluster_keys output (default: ${ROOT}/terraform/rosa-hcp).
  --namespace NS        Namespace for every service (default: ${NS_DEFAULT}).
  -o FILE               Write topology YAML here (default: ${ROOT}/isotope-multicluster/topology/generated-from-terraform.yaml).
  --stdout-only         Print YAML to stdout only; do not write -o.
  --print-env           Print shell exports for ISOTOPE_LOGICAL_CLUSTERS and ISOTOPE_NAMESPACE_MAP to stderr.

Requires: terraform (initialized stack), jq.

Logical cluster names in the YAML match kubectl/oc context names (same as terraform output cluster_keys).
EOF
}

STDOUT_ONLY=0
while [[ $# -gt 0 ]]; do
	case "$1" in
	--terraform-dir)
		[[ -n "${2:-}" ]] || die "--terraform-dir requires a value"
		TF_DIR="$2"
		shift 2
		;;
	--namespace)
		[[ -n "${2:-}" ]] || die "--namespace requires a value"
		NS_DEFAULT="$2"
		shift 2
		;;
	-o)
		[[ -n "${2:-}" ]] || die "-o requires a value"
		OUT="$2"
		shift 2
		;;
	--stdout-only)
		STDOUT_ONLY=1
		shift
		;;
	--print-env)
		PRINT_ENV=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		die "unknown option: $1 (try --help)"
		;;
	esac
done

[[ -z "$OUT" ]] && OUT="${ROOT}/isotope-multicluster/topology/generated-from-terraform.yaml"
[[ -d "$TF_DIR" ]] || die "terraform directory not found: $TF_DIR"
command -v terraform >/dev/null 2>&1 || die "terraform not found on PATH"
command -v jq >/dev/null 2>&1 || die "jq not found on PATH"

KEYS_JSON="$(terraform -chdir="$TF_DIR" output -json cluster_keys 2>/dev/null)" ||
	die "terraform output cluster_keys failed (run terraform apply in ${TF_DIR}?)"
mapfile -t KEYS < <(echo "$KEYS_JSON" | jq -r '(if type == "array" then . elif .value then .value else empty end) | .[]')
((${#KEYS[@]} > 0)) || die "no cluster keys in terraform output"

emit_yaml() {
	echo "# Generated by 001-generate-topology-from-terraform.sh — chain across terraform cluster_keys"
	echo "# Regenerate after changing cluster_count / naming; logical cluster fields match kube contexts."
	echo "defaults:"
	echo "  requestSize: 1 KB"
	echo "  responseSize: 1 KB"
	echo "services:"
	local n=${#KEYS[@]}
	local i name next
	for ((i = 0; i < n; i++)); do
		name="svc${i}"
		if ((i == 0)); then
			echo "  - isEntrypoint: true"
			echo "    name: ${name}"
			echo "    namespace: ${NS_DEFAULT}"
			echo "    cluster: ${KEYS[i]}"
			if ((n > 1)); then
				next="svc$((i + 1))"
				echo "    script:"
				echo "      - call:"
				echo "          service: ${next}"
				echo "          hostname: ${next}.global:8080"
			fi
		elif ((i < n - 1)); then
			next="svc$((i + 1))"
			echo "  - name: ${name}"
			echo "    namespace: ${NS_DEFAULT}"
			echo "    cluster: ${KEYS[i]}"
			echo "    script:"
			echo "      - call:"
			echo "          service: ${next}"
			echo "          hostname: ${next}.global:8080"
		else
			echo "  - name: ${name}"
			echo "    namespace: ${NS_DEFAULT}"
			echo "    cluster: ${KEYS[i]}"
		fi
	done
}

logical_clusters_csv() {
	local i s=""
	for ((i = 0; i < ${#KEYS[@]}; i++)); do
		[[ -n "$s" ]] && s+=","
		s+="${KEYS[i]}"
	done
	echo "$s"
}

namespace_map_csv() {
	local i s=""
	for ((i = 0; i < ${#KEYS[@]}; i++)); do
		[[ -n "$s" ]] && s+=","
		s+="${KEYS[i]}:${NS_DEFAULT}"
	done
	echo "$s"
}

write_body() {
	emit_yaml
}

if ((STDOUT_ONLY)); then
	write_body
else
	mkdir -p "$(dirname "$OUT")"
	write_body >"$OUT"
	echo "Wrote topology: $OUT"
fi

if ((PRINT_ENV)); then
	echo "export ISOTOPE_LOGICAL_CLUSTERS=\"$(logical_clusters_csv)\"" >&2
	echo "export ISOTOPE_NAMESPACE_MAP=\"$(namespace_map_csv)\"" >&2
fi
