apiVersion: v1
kind: ServiceAccount
metadata:
  name: spoke-mesh-restart
  namespace: istio-system
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.rbac | quote }}
  {{- end }}
  labels:
    {{- include "spoke-mesh-restart.labels" . | nindent 4 }}
