apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  {{- if or .Values.argoSyncWaves.enabled .Values.service.annotations }}
  annotations:
    {{- if .Values.argoSyncWaves.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.gateway | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "spoke-ingress-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spoke-ingress-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
