{{- if .Values.externalSecretsConfig.enabled }}
apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: cluster
  annotations:
    {{- if .Values.argoSyncWaves.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.externalSecretsConfig | quote }}
    {{- end }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- end }}
