apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscription.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  channel: {{ .Values.subscription.channel | quote }}
  name: {{ .Values.subscription.package | quote }}
  source: {{ .Values.subscription.source | quote }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace | quote }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval | quote }}
