apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.istioCni | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.namespaces | quote }}
  {{- end }}
  labels:
    {{- include "spoke-ossm-operator.labels" . | nindent 4 }}
