{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: {{ .Values.istioNamespace }}
  labels:
    {{- include "istiod-monitor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: istiod
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: "pilot_proxy_convergence_time_bucket|pilot_proxy_convergence_time_sum|pilot_proxy_convergence_time_count|pilot_proxy_queue_time_bucket|pilot_proxy_queue_time_sum|pilot_proxy_queue_time_count|pilot_xds_push_time_bucket|pilot_xds_push_time_sum|pilot_xds_push_time_count|pilot_xds_pushes|pilot_xds|pilot_k8s_cfg_events|pilot_push_triggers|pilot_xds_config_size_bytes_bucket|pilot_xds_config_size_bytes_sum|pilot_xds_config_size_bytes_count"
          action: keep
{{- end }}
