apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.istio | quote }}
  {{- end }}
spec:
  version: {{ .Values.istioVersion | quote }}
  profile: openshift
  namespace: istio-system
  values:
    global:
      meshID: {{ .Values.meshID | quote }}
      network: {{ printf "%s-%s" .Values.clusterName .Values.networkSuffix | quote }}
      multiCluster:
        clusterName: {{ .Values.clusterName | quote }}
      enableReaderRBAC: true
      {{- if .Values.meshNetworks }}
      meshNetworks:
        {{- toYaml .Values.meshNetworks | nindent 8 }}
      {{- end }}
    pilot:
      cni:
        enabled: true
      autoscaleEnabled: {{ .Values.pilot.autoscaleEnabled }}
      {{- if not .Values.pilot.autoscaleEnabled }}
      replicaCount: {{ .Values.pilot.replicaCount }}
      {{- end }}
      {{- with .Values.pilot.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    meshConfig:
      accessLogFile: {{ .Values.accessLogFile | quote }}
      accessLogEncoding: {{ .Values.accessLogEncoding | quote }}
