{{- if .Values.generatorConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.generatorConfigMap.name | quote }}
  namespace: {{ .Values.applicationSetNamespace | quote }}
  labels:
    app.kubernetes.io/name: gitops-hub-external-secrets-operator-appset
data:
  apiVersion: cluster.open-cluster-management.io/v1beta1
  kind: placementdecisions
  statusListKey: decisions
  matchKey: clusterName
{{- end }}
