{{- if .Values.argocdApplicationControllerRbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.argocdApplicationControllerRbac.roleName | quote }}
  namespace: {{ .Values.applicationSetNamespace | quote }}
  labels:
{{- include "gitops-hub-ocm-placement-appset.labels" . | nindent 4 }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applicationsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.argocdApplicationControllerRbac.roleBindingName | quote }}
  namespace: {{ .Values.applicationSetNamespace | quote }}
  labels:
{{- include "gitops-hub-ocm-placement-appset.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.argocdApplicationControllerRbac.roleName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.argocdApplicationControllerRbac.serviceAccountName | quote }}
    namespace: {{ .Values.argocdApplicationControllerRbac.serviceAccountNamespace | quote }}
{{- end }}
