apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istio-eastwestgateway
  namespace: istio-system
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.gateway | quote }}
  {{- end }}
  labels:
    {{- include "spoke-east-west-gateway.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "spoke-east-west-gateway.selectorLabels" . | nindent 6 }}
