apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-eastwestgateway-service-account
  namespace: istio-system
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.gateway | quote }}
  {{- end }}
  labels:
    {{- include "spoke-east-west-gateway.labels" . | nindent 4 }}
