apiVersion: v1
kind: Service
metadata:
  name: istio-eastwestgateway
  namespace: istio-system
  {{- if or .Values.argoSyncWaves.enabled .Values.service.annotations }}
  annotations:
    {{- if .Values.argoSyncWaves.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.gateway | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "spoke-east-west-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spoke-east-west-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443
    - name: tls-istiod
      port: 15012
      protocol: TCP
      targetPort: 15012
    - name: tls-webhook
      port: 15017
      protocol: TCP
      targetPort: 15017
