image:
  repository: registry.redhat.io/openshift4/ose-cli
  tag: latest

deployments:
  - istiod
  - istio-ingressgateway
  - istio-eastwestgateway

rolloutTimeout: 180s

argoSyncWaves:
  enabled: true
  rbac: "-30"
  job: "0"

rbac:
  enabled: true
  argocd:
    namespace: openshift-gitops
    serviceAccountName: openshift-gitops-argocd-application-controller
