{{- if and .Values.canary.enabled .Values.canary.virtualservice.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: propagation-canary
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.canary.virtualservice.host | quote }}
  http:
    - route:
        - destination:
            host: propagation-canary
            port:
              number: {{ .Values.service.port }}
{{- end }}
