{{- if and .Values.canary.enabled .Values.canary.destinationrule.enabled }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: propagation-canary
  namespace: {{ .Values.namespace }}
spec:
  host: propagation-canary.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: false
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        h2UpgradePolicy: DEFAULT
{{- end }}
