apiVersion: v1
kind: Service
metadata:
  name: churn-watcher
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "churn-test.watcher.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "churn-test.watcher.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
