{{- if .Values.managedServiceAccount.create }}
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: {{ .Values.managedServiceAccount.name }}-rbac
  namespace: {{ .Values.managedCluster.name }}
spec:
  workload:
    manifests:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: open-cluster-management:{{ .Values.managedServiceAccount.name }}
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            name: {{ .Values.managedServiceAccount.name }}
            namespace: open-cluster-management-agent-addon
{{- end }}
