{{- if .Values.managedServiceAccount.create }}
{{- if not .Values.managedCluster.name }}
{{- fail "managedCluster.name is required for ManagedServiceAccount resources" }}
{{- end }}
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: {{ .Values.managedCluster.name }}
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: {{ .Values.managedServiceAccount.name }}
  namespace: {{ .Values.managedCluster.name }}
spec:
  rotation: {}
{{- end }}
