apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hub-kubeconfig-from-argosecret.storeServiceAccount" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.secretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-eso-kubernetes-store" (include "hub-kubeconfig-from-argosecret.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.secretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews", "selfsubjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-eso-kubernetes-store" (include "hub-kubeconfig-from-argosecret.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.secretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-eso-kubernetes-store" (include "hub-kubeconfig-from-argosecret.fullname" .) | trunc 63 | trimSuffix "-" | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hub-kubeconfig-from-argosecret.storeServiceAccount" . | quote }}
    namespace: {{ .Values.namespace | quote }}
