apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "hub-kubeconfig-from-argosecret.secretStoreName" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.secretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.namespace | quote }}
      auth:
        serviceAccount:
          name: {{ include "hub-kubeconfig-from-argosecret.storeServiceAccount" . | quote }}
