apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "kubeconfig-%s" .Values.clusterName | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.externalSecret | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  refreshInterval: {{ .Values.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "hub-kubeconfig-from-argosecret.secretStoreName" . | quote }}
    kind: SecretStore
  target:
    name: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        kubeconfig: |
{{ .Files.Get "files/eso-kubeconfig.tpl" | nindent 10 }}
        bearer-token: |
{{ .Files.Get "files/eso-bearer-token.tpl" | nindent 10 }}
        ca.crt: |
{{ .Files.Get "files/eso-ca-cert.tpl" | nindent 10 }}
  data:
    - secretKey: argoConfig
      remoteRef:
        key: {{ include "hub-kubeconfig-from-argosecret.sourceSecretName" . | quote }}
        property: config
    - secretKey: argoName
      remoteRef:
        key: {{ include "hub-kubeconfig-from-argosecret.sourceSecretName" . | quote }}
        property: name
    - secretKey: argoServer
      remoteRef:
        key: {{ include "hub-kubeconfig-from-argosecret.sourceSecretName" . | quote }}
        property: server
