{{- if and .Values.spokeSecretStore.enabled .Values.clusterServer }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "hub-kubeconfig-from-argosecret.spokeSecretStoreName" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.spokeSecretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: spoke-secretstore
spec:
  provider:
    kubernetes:
{{- with .Values.spokeSecretStore.remoteNamespace }}
      remoteNamespace: {{ . | quote }}
{{- end }}
      server:
        url: {{ .Values.clusterServer | quote }}
        caProvider:
          type: Secret
          name: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
          key: ca.crt
      auth:
        token:
          bearerToken:
            secretRef:
              name: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
              key: bearer-token
{{- end }}
