{{- if and .Values.pushSecret.enabled .Values.spokeSecretStore.enabled .Values.clusterName }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "push-kubeconfig-%s" .Values.clusterName | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.pushSecret | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-kubeconfig-from-argosecret.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: pushsecret
spec:
  refreshInterval: {{ .Values.pushSecret.refreshInterval | quote }}
  secretStoreRefs:
    - labelSelector:
        matchLabels:
          {{- toYaml .Values.pushSecret.storeMatchLabels | nindent 10 }}
  selector:
    secret:
      name: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
  data:
    - match:
        secretKey: kubeconfig
        remoteRef:
          remoteKey: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
          property: kubeconfig
    - match:
        secretKey: bearer-token
        remoteRef:
          remoteKey: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
          property: bearer-token
    - match:
        secretKey: ca.crt
        remoteRef:
          remoteKey: {{ include "hub-kubeconfig-from-argosecret.targetSecretName" . | quote }}
          property: ca.crt
{{- end }}
