apiVersion: v1
kind: Service
metadata:
  name: mesh-verify-echo
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mesh-verify.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mesh-verify.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
