apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "hub-mesh-push-secrets.secretStoreName" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.secretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-mesh-push-secrets.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.sourceSecretsNamespace | quote }}
{{- if .Values.kubernetesAPI.caFromConfigMap.enabled }}
      server:
{{- with .Values.kubernetesAPI.serverURL }}
        url: {{ . | quote }}
{{- end }}
        caProvider:
          type: ConfigMap
          name: {{ .Values.kubernetesAPI.caFromConfigMap.name | quote }}
          key: {{ .Values.kubernetesAPI.caFromConfigMap.key | quote }}
{{- end }}
      auth:
        serviceAccount:
          name: {{ include "hub-mesh-push-secrets.storeServiceAccount" . | quote }}
          namespace: {{ .Values.namespace | quote }}
