{{- if .Values.cacerts.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "cacerts-%s" .Values.clusterName | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.externalSecret | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-mesh-push-secrets.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  refreshInterval: {{ .Values.cacerts.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "hub-mesh-push-secrets.secretStoreName" . | quote }}
    kind: SecretStore
  target:
    name: {{ include "hub-mesh-push-secrets.cacertsTargetSecretName" . | quote }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ca-cert.pem: |-
          {{ "{{ .tls_crt }}" }}
        ca-key.pem: |-
          {{ "{{ .tls_key }}" }}
        root-cert.pem: |-
          {{ "{{ .ca_crt }}" }}
        cert-chain.pem: |-
          {{ "{{ .tls_crt }}{{ .ca_crt }}" }}
  data:
    - secretKey: tls_crt
      remoteRef:
        key: {{ include "hub-mesh-push-secrets.cacertsSourceSecretName" . | quote }}
        property: tls.crt
    - secretKey: tls_key
      remoteRef:
        key: {{ include "hub-mesh-push-secrets.cacertsSourceSecretName" . | quote }}
        property: tls.key
    - secretKey: ca_crt
      remoteRef:
        key: {{ include "hub-mesh-push-secrets.cacertsSourceSecretName" . | quote }}
        property: ca.crt
{{- end }}
