{{- if and .Values.spokeSecretStore.enabled .Values.clusterServer .Values.clusterName }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "hub-mesh-push-secrets.spokeSecretStoreName" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.spokeSecretStore | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-mesh-push-secrets.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: spoke-secretstore
    {{- with .Values.spokeSecretStore.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.spokeTargetNamespace | quote }}
      server:
        url: {{ .Values.clusterServer | quote }}
{{- if not .Values.spokeSecretStore.skipCAProvider }}
        caProvider:
          type: Secret
          name: {{ include "hub-mesh-push-secrets.kubeconfigSourceSecretName" . | quote }}
          key: ca.crt
{{- end }}
      auth:
        token:
          bearerToken:
            name: {{ include "hub-mesh-push-secrets.kubeconfigSourceSecretName" . | quote }}
            key: bearer-token
{{- end }}
