{{- if and .Values.cacerts.enabled .Values.spokeSecretStore.enabled .Values.clusterName }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "push-cacerts-%s" .Values.clusterName | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.pushSecret | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-mesh-push-secrets.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: pushsecret-cacerts
spec:
  refreshInterval: {{ .Values.pushSecret.refreshInterval | quote }}
  secretStoreRefs:
    - labelSelector:
        matchLabels:
          hub-mesh-push-secrets/cluster-name: {{ .Values.clusterName | quote }}
  selector:
    secret:
      name: {{ include "hub-mesh-push-secrets.cacertsTargetSecretName" . | quote }}
  data:
    - match:
        secretKey: ca-cert.pem
        remoteRef:
          remoteKey: cacerts
          property: ca-cert.pem
    - match:
        secretKey: ca-key.pem
        remoteRef:
          remoteKey: cacerts
          property: ca-key.pem
    - match:
        secretKey: root-cert.pem
        remoteRef:
          remoteKey: cacerts
          property: root-cert.pem
    - match:
        secretKey: cert-chain.pem
        remoteRef:
          remoteKey: cacerts
          property: cert-chain.pem
{{- end }}
