{{- if and .Values.kubeconfig.enabled .Values.spokeSecretStore.enabled .Values.clusterName }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "push-remote-secret-%s" .Values.clusterName | trunc 63 | trimSuffix "-" | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.argoSyncWaves.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWaves.pushSecret | quote }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "hub-mesh-push-secrets.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: pushsecret-remote-secret
spec:
  refreshInterval: {{ .Values.kubeconfig.refreshInterval | quote }}
  secretStoreRefs:
    - labelSelector:
        matchLabels:
          hub-mesh-push-secrets/push-target: "true"
  selector:
    secret:
      name: {{ include "hub-mesh-push-secrets.kubeconfigSourceSecretName" . | quote }}
  template:
    metadata:
      labels:
        istio/multiCluster: "true"
      annotations:
        networking.istio.io/cluster: {{ .Values.clusterName | quote }}
    engineVersion: v2
    data:
      {{ .Values.clusterName }}: "{{ "{{ .kubeconfig }}" }}"
  data:
    - match:
        secretKey: kubeconfig
        remoteRef:
          remoteKey: {{ printf "istio-remote-secret-%s" .Values.clusterName | quote }}
          property: {{ .Values.clusterName | quote }}
{{- end }}
